---
title: "en.ja Quote"
baseurl: "http://quote.enja.io"
params:
  AuthorName: "Yuya Saito"
  Bio: "Front-end Develper by day, translator by night."
  Description: "日本語訳したクォートのリマインダ用ログ"
  Twitter: "cssradar"
  Googleplus: "+YuyaSaito"
  Github: "studiomohawk"
  Pinboard: "studiomohawk"
  Issue: "https://github.com/enja/quote/issues"
...
