---
title: "Myriel"
baseurl: "http://studiomohawk.github.io/myriel/"
params:
  AuthorName: "Yuya Saito"
  Bio: "Front-end Develper by day, translator by night."
  Description: "Myriel is modularized minimum blog theme for Hugo."
  Twitter: "cssradar"
  Googleplus: "+YuyaSaito"
  Github: "studiomohawk"
  Pinboard: "studiomohawk"
  Issue: "https://github.com/studiomohawk/myriel/issues"
...
